// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gossip.proto

#include "gossip.pb.h"
#include "gossip.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace event_store {
namespace client {
namespace gossip {

static const char* Gossip_method_names[] = {
  "/event_store.client.gossip.Gossip/Read",
};

std::unique_ptr< Gossip::Stub> Gossip::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Gossip::Stub> stub(new Gossip::Stub(channel));
  return stub;
}

Gossip::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Read_(Gossip_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Gossip::Stub::Read(::grpc::ClientContext* context, const ::event_store::client::Empty& request, ::event_store::client::gossip::ClusterInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Read_, context, request, response);
}

void Gossip::Stub::experimental_async::Read(::grpc::ClientContext* context, const ::event_store::client::Empty* request, ::event_store::client::gossip::ClusterInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, std::move(f));
}

void Gossip::Stub::experimental_async::Read(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::event_store::client::gossip::ClusterInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, std::move(f));
}

void Gossip::Stub::experimental_async::Read(::grpc::ClientContext* context, const ::event_store::client::Empty* request, ::event_store::client::gossip::ClusterInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, reactor);
}

void Gossip::Stub::experimental_async::Read(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::event_store::client::gossip::ClusterInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::event_store::client::gossip::ClusterInfo>* Gossip::Stub::AsyncReadRaw(::grpc::ClientContext* context, const ::event_store::client::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::event_store::client::gossip::ClusterInfo>::Create(channel_.get(), cq, rpcmethod_Read_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::event_store::client::gossip::ClusterInfo>* Gossip::Stub::PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::event_store::client::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::event_store::client::gossip::ClusterInfo>::Create(channel_.get(), cq, rpcmethod_Read_, context, request, false);
}

Gossip::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gossip_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Gossip::Service, ::event_store::client::Empty, ::event_store::client::gossip::ClusterInfo>(
          [](Gossip::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::event_store::client::Empty* req,
             ::event_store::client::gossip::ClusterInfo* resp) {
               return service->Read(ctx, req, resp);
             }, this)));
}

Gossip::Service::~Service() {
}

::grpc::Status Gossip::Service::Read(::grpc::ServerContext* context, const ::event_store::client::Empty* request, ::event_store::client::gossip::ClusterInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace event_store
}  // namespace client
}  // namespace gossip

