// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: monitoring.proto

#include "monitoring.pb.h"
#include "monitoring.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace event_store {
namespace client {
namespace monitoring {

static const char* Monitoring_method_names[] = {
  "/event_store.client.monitoring.Monitoring/Stats",
};

std::unique_ptr< Monitoring::Stub> Monitoring::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Monitoring::Stub> stub(new Monitoring::Stub(channel));
  return stub;
}

Monitoring::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Stats_(Monitoring_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::event_store::client::monitoring::StatsResp>* Monitoring::Stub::StatsRaw(::grpc::ClientContext* context, const ::event_store::client::monitoring::StatsReq& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::event_store::client::monitoring::StatsResp>::Create(channel_.get(), rpcmethod_Stats_, context, request);
}

void Monitoring::Stub::experimental_async::Stats(::grpc::ClientContext* context, ::event_store::client::monitoring::StatsReq* request, ::grpc::experimental::ClientReadReactor< ::event_store::client::monitoring::StatsResp>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::event_store::client::monitoring::StatsResp>::Create(stub_->channel_.get(), stub_->rpcmethod_Stats_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::event_store::client::monitoring::StatsResp>* Monitoring::Stub::AsyncStatsRaw(::grpc::ClientContext* context, const ::event_store::client::monitoring::StatsReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::event_store::client::monitoring::StatsResp>::Create(channel_.get(), cq, rpcmethod_Stats_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::event_store::client::monitoring::StatsResp>* Monitoring::Stub::PrepareAsyncStatsRaw(::grpc::ClientContext* context, const ::event_store::client::monitoring::StatsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::event_store::client::monitoring::StatsResp>::Create(channel_.get(), cq, rpcmethod_Stats_, context, request, false, nullptr);
}

Monitoring::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Monitoring_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Monitoring::Service, ::event_store::client::monitoring::StatsReq, ::event_store::client::monitoring::StatsResp>(
          [](Monitoring::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::event_store::client::monitoring::StatsReq* req,
             ::grpc_impl::ServerWriter<::event_store::client::monitoring::StatsResp>* writer) {
               return service->Stats(ctx, req, writer);
             }, this)));
}

Monitoring::Service::~Service() {
}

::grpc::Status Monitoring::Service::Stats(::grpc::ServerContext* context, const ::event_store::client::monitoring::StatsReq* request, ::grpc::ServerWriter< ::event_store::client::monitoring::StatsResp>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace event_store
}  // namespace client
}  // namespace monitoring

